baseURL: 'localhost'
languageCode: nl-nl
title: RECEPTEN
theme: 
  - hyde
  - hugo-easy-gallery
  
defaultContentLanguage: nl
enableInlineShortcodes: true
summarylength: 70
paginate: 5

params:
  description: Ik ben Stijn. Ik hou van Eten
  dateFormat: monday 2 Januari 2006

taxonomies:
  category: categories
  tag: tags

# Menu
menu:
  main:
    - identifier: buurtinbeeld
      name: Buurt in Beeld
      url: /buurtinbeeld/
      weight: 2
    - identifier: zwemfest
      name: Zwemfest
      url: /zwemfest/
      weight: 3
    - identifier: verenigingbuurland
      name: Vereniging Buurland
      url: /vereniging-buurland/
      weight: 4
    - identifier: media
      name: In de media
      url: /media/
      weight: 5
    - identifier: blog
      name: Berichten
      url: /berichten/
      weight: 6
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 7
