# Your base url
baseURL = "http://localhost/my-title"
# Your page title
title = "Stijns recepten"
theme = "cuisine-book"
# (Optional) Set this to true to enable Author.
enableGitInfo = false

[params]
  author = "Stijn"
  description = "Ik ben Stijn. Ik hou van eten."
  # (Optional) Your logo in the header navbar which has to be stored in static folder.
  # If the logo is /static/logo.png then the path would be 'logo.png'
  logo = "logo.png"
  # (Optional) Enable comments template on pages
  # By default partials/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  comment = False
  # Set source repository location.
#  repo = 'https://github.com/ntk148v/mammam'
  # Enable 'Edit' links.
  # Disabled by default. Uncomment to enable. Requires 'repo' param.
  # Path must point to the site directory.
#  editpath = 'edit/master'
  # Enable 'Add' links.
  # Disabled by default. Uncomment to enable. Requires 'repo' param.
  # Path must point to the site directory.
 # newpath = 'new/master'