backend:
  name: git-gateway
  repo: iroQuai/recepten
  branch: 'main'
media_folder: static/images
public_folder: /images
collections:
  - name: "recepten"
    label: "Recepten"
    label_singular: "Recept"
    # Where to store posts (relative to the project root)
    folder: "content/recepten"
    # Support Hugo page bundles that puts index.md and images in folders named by slug
    path: "{{slug}}/index"
    media_folder: "/content/recepten/{{slug}}/"
    public_folder: "/content/recepten/{{slug}}/"
    create: true
    editor:
      preview: false
    fields:
      - { label: 'titel', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', choose_url: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
