site_url: https://recepten.stijnbiemans.nl
show_preview_links: true
locale: 'nl'

backend:
  name: git-gateway
  repo: iroQuai/recepten
  branch: 'main'

media_folder: static/images
public_folder: /images

collections:
  - name: "recepten"
    label: "Recepten"
    label_singular: "Recept"
    # Where to store posts (relative to the project root)
    folder: "content/recepten"
    # Support Hugo page bundles that puts index.md and images in folders named by slug
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    editor:
      preview: false
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'titel', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Omschrijving', name: 'description', widget: 'string' }
      - { label: 'Afbeelding', name: 'image', widget: 'image', choose_url: false }
      - { label: 'Inhoud', name: 'body', widget: 'markdown' }
